apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-node-js
spec:
  replicas: 3
  selector:
    matchLabels:
      app: book-node-js
  template:
    metadata:
      labels:
        app: book-node-js
    spec:
      containers:
      - name: book-node-js
        image: zeinab817/nodejs-app:v1
        ports:
        - containerPort: 3000
        command: ["sh", "-c", "sleep 100 && node server.js"]
