apiVersion: v1
kind: Service
metadata:
  name: book-node-js-service
spec:
  type: LoadBalancer
  selector:
    app: book-node-js
  ports:
    - port: 3000         # The port that the service will expose
      targetPort: 3000   # The port on the container that the service should forward to
